% %Create a linearArray with dipoleFolded element.
% Generated by MATLAB(R) 9.7 and Antenna Toolbox 4.1.
% Generated on: 07-Jun-2020 09:51:19

%% Array Properties 
%Define Array
arrayObject = linearArray;

arrayObject.NumElements = 5;

%Define Array Elements
Element1 = dipoleFolded;
arrayObject.Element = [Element1 ];

% Design array at frequency 70500000Hz
arrayObject = design(arrayObject,70500000,Element1);
%arrayObject Properties Changed
arrayObject.PhaseShift = 90;
arrayObject.Tilt = 180;

%Element1 Properties Changed
arrayObject.Element(1).Tilt = 180;
% Update load properties 
arrayObject.Element(1).Load.Impedance = 280;

%% Array Analysis 
% Show for linearArray
figure;
show(arrayObject) 
% Layout for linearArray
figure;
layout(arrayObject) 
% Pattern for linearArray
plotFrequency = 70500000; Termination = 50;
figure;
pattern(arrayObject, plotFrequency,'Termination',Termination);
% calculate BW and angels
[bw, angles] = beamwidth(arrayObject, plotFrequency, 0, 1:1:360)
% Azimuth for linearArray
plotFrequency = 70500000; azRange = 0:5:360; Termination = 50;
figure;
pattern(arrayObject, plotFrequency,azRange,0,'Termination',Termination);
% Beam Scanning
c = physconst('lightspeed');
lambda = c/plotFrequency;
N = 5;
dx= 0.49*lambda;
scanangle = [120 0];
ps = phaseshift(plotFrequency,dx,scanangle,N);
arrayObject.PhaseShift = ps;
patternazfig2 = figure;
pattern(arrayObject,plotFrequency,azRange,0,'CoordinateSystem','rectangular')
axis([0 180 -25 15])
% Elevation for linearArray
plotFrequency = 70500000; elRange = 0:5:360; Termination = 50;
figure;
pattern(arrayObject, plotFrequency,0,elRange,'Termination',Termination);
% Impedance for linearArray
freqRange = [63450000           64155000           64860000           65565000           66270000           66975000           67680000           68385000           69090000           69795000           70500000           71205000           71910000           72615000           73320000           74025000           74730000           75435000           76140000           76845000           77550000];
figure;
impedance(arrayObject, freqRange) 
% Sparameters for linearArray
freqRange = [63450000           64155000           64860000           65565000           66270000           66975000           67680000           68385000           69090000           69795000           70500000           71205000           71910000           72615000           73320000           74025000           74730000           75435000           76140000           76845000           77550000]; RefImpedance = 50;
figure;
rfplot(sparameters(arrayObject, freqRange,RefImpedance)); 

%% Grating Lobes אונות שריג
arrayObject.NumElements = 5;
arrayObject.ElementSpacing = lambda/2;
D_half_lambda = pattern(arrayObject,plotFrequency,azRange,0,'CoordinateSystem','rectangular');
arrayObject.ElementSpacing = 0.75*lambda;
D_three_quarter_lambda = pattern(arrayObject,plotFrequency,azRange,0,'CoordinateSystem','rectangular');
arrayObject.ElementSpacing = 1.5*lambda;
D_lambda = pattern(arrayObject,plotFrequency,azRange,0,'CoordinateSystem','rectangular');
patterngrating1 = figure;
plot(azRange,D_half_lambda,azRange,D_three_quarter_lambda,azRange,D_lambda,'LineWidth',1.5);
grid on
xlabel('Azimuth (deg)')
ylabel('Directivity (dBi)')
title('Array Pattern (Elevation = 0 deg)')
legend('d=\lambda/2','d=0.75\lambda','d=1.5\lambda','Location','best')
%% Grating Lobes המשך
% Compared to the landa/2 spaced array, the 1.5 lamda spaced array shows 2 additional 
% equally strong peaks in the visible space - the grating lobes. 
% The 0.75 lamda  spaced array still has a single unique beam peak
% at zero scan off broadside (azimuthal angle of 90 deg). Scan this array off broadside
% to observe appearance of the grating lobes
arrayObject.ElementSpacing = 0.75*lambda;
azscan = 45:10:135;
scanangle = [azscan ;zeros(1,numel(azscan))];
D_scan = nan(numel(azscan),numel(azRange));
legend_string1 = cell(1,numel(azscan));
for i = 1:numel(azscan)
    ps = phaseshift(plotFrequency,dx,scanangle(:,i),N);
    arrayObject.PhaseShift = ps;
    D_scan(i,:) = pattern(arrayObject,plotFrequency,azRange,0,'CoordinateSystem','rectangular');
    legend_string1{i} = strcat('scan = ',num2str(azscan(i)),' deg');
end
patterngrating2 = figure;
plot(azRange,D_scan,'LineWidth',1)
xlabel('Azimuth (deg)')
ylabel('Directivity (dBi)')
title('Scan Pattern for 0.75\lambda Spacing Array ((Elevation = 0 deg)')
grid on
legend(legend_string1,'Location','best')
%%
% Mutual Coupling באנטנה שלנו אפסי צימוד משותף
% Mutual coupling is the phenomenon whereby currents developed on each element 
% in the array do not depend only on their own excitation,
% but have contributions from other elements as well. To study this effect,
% we will simplify the array to a 2-element case similar to [1].
arrayObject.NumElements = 5;
arrayObject.AmplitudeTaper = 1;
arrayObject.PhaseShift = 0;
% To observe the effect of mutual coupling, vary the spacing between the array elements
% and plot the variation in , mutual impedance between the pair of dipoles in the array [1].
% Since the elements are parallel to each other, the coupling is strong.
spacing = (lambda/2:0.05:2).*lambda;
Z12 = nan(1,numel(spacing));
for i = 1:numel(spacing)
    arrayObject.ElementSpacing = spacing(i);
    s = sparameters(arrayObject,plotFrequency,real(Z_resonant_dipole));
    S = s.Parameters;
    Z12(i) = 2*S(1,2)*70/((1 - S(1,1))*(1- S(2,2)) - S(1,2)*S(2,1));
end
mutualZ12fig = figure;
plot(spacing./lambda,real(Z12),spacing./lambda,imag(Z12),'LineWidth',2)
xlabel('Spacing, d/\lambda')
ylabel('Impedance (\Omega)')
grid on
title('Mutual Impedance Variation With Spacing')
legend('Resistance','Reactance')