% %Create a circularArray with dipoleFolded element.
% Generated by MATLAB(R) 9.7 and Antenna Toolbox 4.1.
% Generated on: 07-Jun-2020 15:40:38

%% Array Properties 
%Define Array
arrayObject = circularArray;

arrayObject.NumElements = 6;

%Define Array Elements
Element1 = dipoleFolded;
arrayObject.Element = [Element1 ];

% Design array at frequency 70500000Hz
arrayObject = design(arrayObject,70500000,Element1);
%arrayObject Properties Changed
arrayObject.PhaseShift = 90;
arrayObject.Tilt = 180;

%Element1 Properties Changed
arrayObject.Element(1).Tilt = 180;
% Update load properties 
arrayObject.Element(1).Load.Impedance = 280;

%% Array Analysis 
% Show for circularArray
figure;
show(arrayObject) 
% Layout for circularArray
figure;
layout(arrayObject) 
% Pattern for circularArray
plotFrequency = 70500000; Termination = 50;
figure;
pattern(arrayObject, plotFrequency,'Termination',Termination);
%%
figure;
arrayFactor(arrayObject, plotFrequency);
% Azimuth for circularArray
plotFrequency = 70500000; azRange = 0:5:360; Termination = 50;
figure;
pattern(arrayObject, plotFrequency,azRange,0,'Termination',Termination);
% calculate BW and angels
[bw, angles] = beamwidth(arrayObject, plotFrequency, 0, 1:1:360)
% Calculate the Directivity of Array
[Directivity] = pattern(arrayObject,plotFrequency,0,90)
% Calculate EH Fields of Array
[E,H] = EHfields(arrayObject,plotFrequency,[0;0;1])
% Elevation for circularArray
plotFrequency = 70500000; elRange = 0:5:360; Termination = 50;
figure;
pattern(arrayObject, plotFrequency,0,elRange,'Termination',Termination);
% Impedance for circularArray
freqRange = [63450000           64155000           64860000           65565000           66270000           66975000           67680000           68385000           69090000           69795000           70500000           71205000           71910000           72615000           73320000           74025000           74730000           75435000           76140000           76845000           77550000];
figure;
impedance(arrayObject, freqRange) 
% Sparameters for circularArray
freqRange = [63450000           64155000           64860000           65565000           66270000           66975000           67680000           68385000           69090000           69795000           70500000           71205000           71910000           72615000           73320000           74025000           74730000           75435000           76140000           76845000           77550000]; RefImpedance = 50;
figure;
rfplot(sparameters(arrayObject, freqRange,RefImpedance)); 
%% Calculate Return Loss of Array
figure;
returnLoss(arrayObject,60e6:1e6:70e6,72)

%%
% Beam Scanning
c = physconst('lightspeed');
lambda = c/plotFrequency;
N = 6;
dx= 0.49*lambda;
scanangle = [120 0];
ps = phaseshift(plotFrequency,dx,scanangle,N);
arrayObject.PhaseShift = ps;
patternazfig2 = figure;
pattern(arrayObject,plotFrequency,azRange,0,'CoordinateSystem','rectangular')
axis([0 180 -25 15]) 

