% Create a dipoleFolded antenna
% Generated by MATLAB(R) 9.7 and Antenna Toolbox 4.1.
% Generated on: 02-Jun-2020 09:52:38

%% Antenna Properties 
% Design antenna at frequency 70500000Hz
antennaObject = design(dipoleFolded,70500000);
% Properties changed 
antennaObject.Tilt = 180;
% Update load properties 
antennaObject.Load.Impedance = 280;

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 70500000;
% Define frequency range 
freqRange = (63.45:0.705:77.55) * 1e6;
% calculate BW and angels
[bw, angles] = beamwidth(antennaObject, plotFrequency, 0, 1:1:360)
% show for dipoleFolded
figure;
show(antennaObject) 
% current for dipoleFolded
figure;
current(antennaObject, plotFrequency) 
% pattern for dipoleFolded
figure;
pattern(antennaObject, plotFrequency)
% Calculate the Directivity 
[Directivity] = pattern(antennaObject,plotFrequency,0,90)
% Calculate EH Fields of Array
[E,H] = EHfields(antennaObject,plotFrequency,[0;0;1])
% azimuth for dipoleFolded
figure;
patternAzimuth(antennaObject, plotFrequency) 
% elevation for dipoleFolded
figure;
patternElevation(antennaObject, plotFrequency) 
% impedance for dipoleFolded
figure;
impedance(antennaObject, freqRange) 
% s11 for dipoleFolded
figure;
s = sparameters(antennaObject, freqRange); 
rfplot(s) 
figure;
vswr (antennaObject, freqRange, 70)

